# Generated by Django 3.2.7 on 2021-09-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20210930_0819'),
        ('Sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=None, to='Account.seller'),
        ),
    ]
