# Generated by Django 3.2.7 on 2021-10-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0003_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ptype',
            field=models.CharField(choices=[('stell', 'stell'), ('iron', 'iron'), ('brass', 'brass'), ('aluminium,', 'aluminium'), ('copper', 'copper')], max_length=50, null=True),
        ),
    ]
