# Generated by Django 3.2.7 on 2021-10-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0008_alter_product_ptype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pdesc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ptype',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('brass', 'brass'), ('iron', 'iron'), ('copper', 'copper'), ('aluminium,', 'aluminium'), ('stell', 'stell')], default='copper', max_length=50, null=True),
        ),
    ]
