# Generated by Django 3.2.7 on 2021-10-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0010_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('aluminium,', 'aluminium'), ('stell', 'stell'), ('brass', 'brass'), ('copper', 'copper'), ('iron', 'iron')], default='copper', max_length=50, null=True),
        ),
    ]
