# Generated by Django 3.2.7 on 2021-10-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0012_auto_20211002_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('stell', 'stell'), ('aluminium,', 'aluminium'), ('iron', 'iron'), ('copper', 'copper'), ('brass', 'brass')], default='copper', max_length=50, null=True),
        ),
    ]
