# Generated by Django 3.2.7 on 2021-10-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0013_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('stell', 'stell'), ('brass', 'brass'), ('iron', 'iron'), ('aluminium,', 'aluminium'), ('copper', 'copper')], default='copper', max_length=50, null=True),
        ),
    ]
