# Generated by Django 3.2.7 on 2021-10-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0017_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('stell', 'stell'), ('iron', 'iron'), ('aluminium,', 'aluminium'), ('copper', 'copper'), ('brass', 'brass')], default='copper', max_length=50, null=True),
        ),
    ]
