# Generated by Django 3.2.7 on 2021-10-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0018_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('iron', 'iron'), ('brass', 'brass'), ('stell', 'stell'), ('copper', 'copper'), ('aluminium,', 'aluminium')], default='copper', max_length=50, null=True),
        ),
    ]
