# Generated by Django 3.2.7 on 2021-10-05 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0007_alter_seller_user'),
        ('Sell', '0015_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('placed', 'placed'), ('conplete', 'complete'), ('dispatched', 'dispatched'), ('confirmed', 'confirmed')], default='placed', max_length=50, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Account.buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porders', to='Sell.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Account.seller')),
            ],
        ),
    ]
