# Generated by Django 3.2.7 on 2021-10-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_seller_user'),
        ('Buy', '0002_auto_20211005_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borders', to='Account.buyer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorders', to='Account.seller'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('conplete', 'complete'), ('placed', 'placed'), ('confirmed', 'confirmed'), ('dispatched', 'dispatched')], default='placed', max_length=50, null=True),
        ),
    ]
