# Generated by Django 3.2.7 on 2021-10-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatch_slip',
            field=models.FileField(blank=True, null=True, upload_to='docOrder/dispatch/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='docOrder/invoices/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('conplete', 'complete'), ('dispatched', 'dispatched'), ('placed', 'placed'), ('confirmed', 'confirmed')], default='placed', max_length=50, null=True),
        ),
    ]
