# Generated by Django 3.2.7 on 2021-10-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0006_auto_20211005_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_slip',
            field=models.FileField(blank=True, null=True, upload_to='docOrder/payment/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('placed', 'placed'), ('dispatched', 'dispatched'), ('conplete', 'complete')], default='placed', max_length=50, null=True),
        ),
    ]
