# Generated by Django 3.2.7 on 2021-09-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Account.user')),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Account.user')),
                ('gstin', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
    ]
