# Generated by Django 3.2.7 on 2021-09-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20210929_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='co_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='gstin',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='co_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gstin',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
