# Generated by Django 3.2.7 on 2021-09-30 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210930_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='co_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='co_name',
            new_name='company_name',
        ),
    ]
