# Generated by Django 3.2.7 on 2021-09-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20210930_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='company_name',
            new_name='company',
        ),
    ]
